"""LLM 客户端 —— ModelClient、ResponseEvent、多 provider 适配。

设计文档：docs/architecture/llm-client.md
"""

from taifeng.llm.client import (
    ModelCapabilities,
    ModelClient,
    ModelClientSession,
    model_capabilities,
)
from taifeng.llm.errors import (
    AuthenticationError,
    CancelledError,
    ContentFilterError,
    ContextOverflowError,
    FailureClass,
    InvalidRequestError,
    LLMError,
    RateLimitError,
    RequestTooLargeError,
    ServerError,
    TransientNetworkError,
    classify_failure,
    suggested_action_for,
)
from taifeng.llm.events import EventKind, ResponseEvent
from taifeng.llm.image_input import (
    DISABLED_IMAGE_POLICY,
    ConservativeImageCostEstimator,
    ImageAttachmentV1,
    ImageInputPolicy,
    InputCostEstimator,
    OpenAIImageCostEstimator,
)
from taifeng.llm.recovery import RecoveryPlan, RecoveryStep, recommend_recovery
from taifeng.llm.retry import RetryConfig, retry_async
from taifeng.llm.types import (
    ApiFunctionCallItem,
    ApiFunctionCallOutputItem,
    ApiInputItem,
    ApiMessage,
    ApiMessageItem,
    ApiProviderStateItem,
    ApiRequest,
    CacheBreakpoint,
    ImagePart,
    ProviderStateEnvelope,
    RateLimitSnapshot,
    ResponseFormatSpec,
    TextPart,
    TokenUsage,
    ToolSpecRef,
)

__all__ = [
    "ApiMessage",
    "ApiMessageItem",
    "ApiFunctionCallItem",
    "ApiFunctionCallOutputItem",
    "ApiInputItem",
    "ApiProviderStateItem",
    "ApiRequest",
    "AuthenticationError",
    "CacheBreakpoint",
    "CancelledError",
    "ContentFilterError",
    "ContextOverflowError",
    "EventKind",
    "FailureClass",
    "InvalidRequestError",
    "LLMError",
    "ImagePart",
    "ImageAttachmentV1",
    "ImageInputPolicy",
    "InputCostEstimator",
    "ModelCapabilities",
    "ModelClient",
    "ModelClientSession",
    "OpenAIImageCostEstimator",
    "RateLimitError",
    "RateLimitSnapshot",
    "ProviderStateEnvelope",
    "RecoveryPlan",
    "RecoveryStep",
    "RequestTooLargeError",
    "ResponseEvent",
    "ResponseFormatSpec",
    "RetryConfig",
    "ServerError",
    "TokenUsage",
    "ConservativeImageCostEstimator",
    "DISABLED_IMAGE_POLICY",
    "TextPart",
    "ToolSpecRef",
    "TransientNetworkError",
    "classify_failure",
    "model_capabilities",
    "recommend_recovery",
    "retry_async",
    "suggested_action_for",
]
